[package]
name = "quinn"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Futures-based QUIC implementation"
keywords = ["quic", "tokio"]
categories = ["network-programming"]
homepage = "https://github.com/djc/quinn"
repository = "https://github.com/djc/quinn"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4.7"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
log = "0.4"
tokio = "0.1"
rand = "0.5"
ring = "0.13"
webpki = "0.18"
webpki-roots = "0.15"

[dependencies.rustls]
# git = "https://github.com/rot256/rustls"
features = ["quic", "dangerous_configuration"]
# branch = "master"
path = "/home/rot256/src/rustls"

[dev-dependencies]
env_logger = "0.5"
untrusted = "0.6.2"
